### ISSUE TITLE
Run code,There's a problem

### ISSUE THREAD

**Issue by Gao1Feng** [sumannewton/apache-ranger-client#2]
Hello, this code appears the following problem, may I ask how to solve it?thank you

`xception in thread "main" feign.FeignException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (BufferedReader); line: 1, column: 2] reading POST http://192.168.232.132:6080/service/xusers/secure/users
	at feign.FeignException.errorReading(FeignException.java:49)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:140)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy3.createUser(Unknown Source)
	at apache.ranger.client.api.UserApis.createUser(UserApis.java:23)
	at RangerClientTest.main(RangerClientTest.java:43)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')`

`public User createUser(final User user) throws RangerClientException {
        return client.createUser(user);
    }`

`/**
 * @author suman.bn
 */
public interface UserFeignClient {

    /*
    Mapper to Ranger User APIs
     */
    @RequestLine("POST /service/xusers/secure/users")
    User createUser(final User user) throws RangerClientException;`

**Comment by sumannewton** [comment]
@Musk1993 Can you post the code?

**Comment by sumannewton** [comment]
Closing this due to inactivity.
